### ISSUE TITLE
deadlocks and core dumps while testing with n concurrent requests

### ISSUE THREAD

**Issue by archibaldhaddock** [chregu/hhvm-newrelic-ext#13]
Hello,

Well, everything is in the subject ! ;-) When I use your extension with only one concurrent request, everything works fine. When I try to send 2 concurrent requests ((I use siege --concurrent=2 --reps=5 on every link of my site), the test ends quickly : hhvm comes to a deadlock or crashes. I use a debug version of hhvm, but the call stack shown in the various core dumps won't help me : seg faults happen  in various memory management calls (new(), free, in jmalloc or stdlib).
I have seen fatal error in hhvm's memory control asserts too (debug mode asserts).
Have you had any problems of this kind ?
Could the newrelic extension make thread-unsafe accesses to  hhvm memory management ?

When I comment newrelic conf in the hdf file, everything is ok again.

Thanks for your great work !

**Comment by chregu** [comment]
JFYI, I worked on the extension a little to make it work on HHVM 3.4 and 3.5, see the branches, if you're interested

I close this ticket for now

**Comment by archibaldhaddock** [comment]
Ok, thanks. I'll have a look !
I could also test the newrelic correction for the memory leak : it works fine.
Thanks again !
