### ISSUE TITLE
Installing on Centos 7, cmake fails

### ISSUE THREAD

**Issue by danielj** [chregu/hhvm-newrelic-ext#15]
#cmake . && make
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- The ASM compiler identification is GNU
-- Found assembler: /bin/cc
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring for HHVM API version 20140829
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NEWRELIC_COLLECTOR_CLIENT_LIBRARY
    linked by target "newrelic" in directory /tmp/hhvm-newrelic-ext
NEWRELIC_COMMON_LIBRARY
    linked by target "newrelic" in directory /tmp/hhvm-newrelic-ext
NEWRELIC_TRANSACTION_LIBRARY
    linked by target "newrelic" in directory /tmp/hhvm-newrelic-ext

-- Configuring incomplete, errors occurred!

**Comment by chregu** [comment]
did you install the New Relic AGent SDK?

````
* Download the Agent SDK http://download.newrelic.com/agent_sdk/
* Copy the library files to /usr/lib or /usr/local/lib: cp nr_agent_sdk*/lib/* /usr/local/lib/
* Copy the header files to /usr/include or /usr/local/include: cp nr_agent_sdk*/include/* /usr/local/include/
* build the extension
```

**Comment by chregu** [comment]
I close this for now, please reopen, if it still doesn't work
