### ISSUE TITLE
Agent not sending datastore segments ?

### ISSUE THREAD

**Issue by gandikun** [chregu/hhvm-newrelic-ext#17]
I added newrelic_pdo_intercept() to my code but I dont get datastore segments in my newrelic dashboard.

In this commit de87eace , i see you comment out all calls to newrelic_segment_datastore_begin. Do you have any reason to do that, I mean that will bring module will not send data store segment, right?

**Comment by chregu** [comment]
shit yeah, I commented that out because it didn't compile when I upgraded to a later HHVM, looking into it.

**Comment by chregu** [comment]
hopefully fixed in https://github.com/chregu/hhvm-newrelic-ext/commit/9781d4373cc167a59f1dcdc265812c46fe7e238e

can you test it?

**Comment by gandikun** [comment]
Still Didn't Work 

I recompile from fresh and replace my old newrelic.so file
put the 'newrelic_pdo_intercept();' at begining of my app script.
restart hhvm and newrelic. But, the data not appear in my newrelic dashboard.


any clue?

for information I using : 
- HHVM 3.5
- Postgress (pgsql-hhvm module -> https://github.com/PocketRent/hhvm-pgsql)
- Laravel 4.2

**Comment by chregu** [comment]
in general no data in new relic? Or just no datastore data?

That part of the code is not by me, but by @jaredkipe, have to setup an example with that to actually test it ;)

**Comment by gandikun** [comment]
yeah, just  no datastore data only,  external or RPM else seems fine. 

I also looking his repo, failing during compile. seems i need to merge with you changes to make it work in HHVM 3.5

**Comment by gandikun** [comment]
It's work perfectly.


Huge Thanks, haha

Regard.

**Comment by chregu** [comment]
great, glad to hear
