### ISSUE TITLE
Ubuntu: hphpsize / phpize

### ISSUE THREAD

**Issue by fabianhenzler** [chregu/hhvm-newrelic-ext#18]
I'm trying to run hphpize --> hphpize: command not found
I'm trying to run phpize --> fabianhenzler@ngmarketplace:~/newrelichhvm/hhvm-newrelic-ext$ phpize                  
     Cannot find config.m4. 
     Make sure that you run '/usr/bin/phpize' in the top level source directory of the module

**Comment by chregu** [comment]
do you have hhvm-dev installed?
Then it should be in /usr/bin/hphpize

**Comment by fabianhenzler** [comment]
i'm sorry! there seemed to be some issue with hhvm-dev --> reinstalled it --> worxx =)
thanks!
