### ISSUE TITLE
newrelic missing browser and db stats

### ISSUE THREAD

**Issue by craigcarnell** [chregu/hhvm-newrelic-ext#9]
Under PHP version of the newrelic plugin I can see browser stats such as page load time as well varnish and database times.

![screen shot 2014-07-31 at 09 37 06](https://cloud.githubusercontent.com/assets/1188869/3761712/e3e7ea68-188d-11e4-9b36-9259451dbd0a.png)

But under the HHVM version that information is missing.

![screen shot 2014-07-31 at 09 37 14](https://cloud.githubusercontent.com/assets/1188869/3761716/e7c01f7a-188d-11e4-9ffa-cf849991bb5b.png)

**Comment by chregu** [comment]
I merged @jaredkipe's work into the for-HHVM-3.4 and for-HHVM-3.5 branch (and soon this will be master). See the README for details
